# Dependencies
markdown:         kramdown
highlighter:      rouge


# build settings
exclude: ["archive","script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
markdown: kramdown
gems:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# Permalinks
#permalink:       pretty # Default
#permalink:        /blog/:categories/:year/:month/:day/:title

# Setup
title:            'MPCS 51033'
tagline:          '...'
description:      'Backends for Mobile Applications'
url:              http://uchicago.cloud
baseurl:          /

# This lets the pagination work with subblog
blogurl:          /blog/

#
author:
  name:           'T. Andrew Binkowski'
  url:            'url?'


# Blog
paginate_path:    "blog/page:num"
paginate:         2

# Custom vars
version:          2.1.0

#cdn:		googledrive.com/host/0B3XzcKIiWyccaUFjZ2RjTndyd2c/
cdn:              http://uchicago.cloud

github:           https://github.com/uchicago-cloud
playground:       https://github.com/uchicago-cloud/mcps51033-2017-spring-playground/
